[package]
name = "list-directory"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
serde = { version = "1.0.219", feature = ["derive"], features = ["derive"] }
serde_json = "1.0.143"
toml = "0.9.5"
